### ISSUE TITLE
generate.pyを実行した際のエラー

### ISSUE THREAD

**Issue by tubasa8814** [Hiroshiba/hihobot#3]
generate.pyを実行した際に

Traceback (most recent call last):
  File "generate.py", line 102, in <module>
    generate(
  File "generate.py", line 46, in generate
    output = output_dir / model_dir.name
AttributeError: 'NoneType' object has no attribute 'name'

というエラーが出たため、

py generate.py --model_dir C:\hihobot-master

と起動したところ新しく

Traceback (most recent call last):
  File "generate.py", line 102, in <module>
    generate(
  File "generate.py", line 51, in generate
    config = create_config(model_config)
  File "C:\hihobot-master\hihobot\config.py", line 64, in create_from_json
    d = json.load(open(s))
TypeError: expected str, bytes or os.PathLike object, not NoneType

とエラーが出てしまいました。
対処法を教えて下さい。

Python:3.8.0
OS:Windows10

**Comment by Hiroshiba** [comment]
--model_configに、学習済みモデルに用いた設定ファイルを指定する必要があります。
他にもオプションを指定する必要があります。近いうちに、各オプションの意味を追記しておきます。
